Repository googleapis/java-redis, pull requests merged in 2020-06, with the labels that each got.

#139 chore: regenerate README versions
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: none

#135 chore: update CONTRIBUTING.md to include code formatting
  CONTRIBUTING.md
  synth.metadata
Labels: automerge, cla: yes, context: full

#140 chore: regenerate with updated protoc
  proto-google-cloud-redis-v1/src/main/java/com/google/cloud/redis/v1/CreateInstanceRequest.java
  proto-google-cloud-redis-v1/src/main/java/com/google/cloud/redis/v1/DeleteInstanceRequest.java
  proto-google-cloud-redis-v1/src/main/java/com/google/cloud/redis/v1/ExportInstanceRequest.java
  proto-google-cloud-redis-v1/src/main/java/com/google/cloud/redis/v1/FailoverInstanceRequest.java
  proto-google-cloud-redis-v1/src/main/java/com/google/cloud/redis/v1/GcsDestination.java
  proto-google-cloud-redis-v1/src/main/java/com/google/cloud/redis/v1/GcsSource.java
  proto-google-cloud-redis-v1/src/main/java/com/google/cloud/redis/v1/GetInstanceRequest.java
  proto-google-cloud-redis-v1/src/main/java/com/google/cloud/redis/v1/ImportInstanceRequest.java
  proto-google-cloud-redis-v1/src/main/java/com/google/cloud/redis/v1/InputConfig.java
  proto-google-cloud-redis-v1/src/main/java/com/google/cloud/redis/v1/Instance.java
  proto-google-cloud-redis-v1/src/main/java/com/google/cloud/redis/v1/ListInstancesRequest.java
  proto-google-cloud-redis-v1/src/main/java/com/google/cloud/redis/v1/ListInstancesResponse.java
  proto-google-cloud-redis-v1/src/main/java/com/google/cloud/redis/v1/LocationMetadata.java
  proto-google-cloud-redis-v1/src/main/java/com/google/cloud/redis/v1/OperationMetadata.java
  proto-google-cloud-redis-v1/src/main/java/com/google/cloud/redis/v1/OutputConfig.java
  proto-google-cloud-redis-v1/src/main/java/com/google/cloud/redis/v1/UpdateInstanceRequest.java
  proto-google-cloud-redis-v1beta1/src/main/java/com/google/cloud/redis/v1beta1/CreateInstanceRequest.java
  proto-google-cloud-redis-v1beta1/src/main/java/com/google/cloud/redis/v1beta1/DeleteInstanceRequest.java
  proto-google-cloud-redis-v1beta1/src/main/java/com/google/cloud/redis/v1beta1/ExportInstanceRequest.java
  proto-google-cloud-redis-v1beta1/src/main/java/com/google/cloud/redis/v1beta1/FailoverInstanceRequest.java
  proto-google-cloud-redis-v1beta1/src/main/java/com/google/cloud/redis/v1beta1/GcsDestination.java
  proto-google-cloud-redis-v1beta1/src/main/java/com/google/cloud/redis/v1beta1/GcsSource.java
  proto-google-cloud-redis-v1beta1/src/main/java/com/google/cloud/redis/v1beta1/GetInstanceRequest.java
  proto-google-cloud-redis-v1beta1/src/main/java/com/google/cloud/redis/v1beta1/ImportInstanceRequest.java
  proto-google-cloud-redis-v1beta1/src/main/java/com/google/cloud/redis/v1beta1/InputConfig.java
  proto-google-cloud-redis-v1beta1/src/main/java/com/google/cloud/redis/v1beta1/Instance.java
  proto-google-cloud-redis-v1beta1/src/main/java/com/google/cloud/redis/v1beta1/ListInstancesRequest.java
  proto-google-cloud-redis-v1beta1/src/main/java/com/google/cloud/redis/v1beta1/ListInstancesResponse.java
  proto-google-cloud-redis-v1beta1/src/main/java/com/google/cloud/redis/v1beta1/LocationMetadata.java
  proto-google-cloud-redis-v1beta1/src/main/java/com/google/cloud/redis/v1beta1/OutputConfig.java
  proto-google-cloud-redis-v1beta1/src/main/java/com/google/cloud/redis/v1beta1/UpdateInstanceRequest.java
  proto-google-cloud-redis-v1beta1/src/main/java/com/google/cloud/redis/v1beta1/UpgradeInstanceRequest.java
  synth.metadata
Labels: automerge, cla: yes, context: full

#143 docs: change relative URLs to absolute URLs to fix broken links
  google-cloud-redis/src/main/java/com/google/cloud/redis/v1/CloudRedisClient.java
  google-cloud-redis/src/main/java/com/google/cloud/redis/v1beta1/CloudRedisClient.java
  grpc-google-cloud-redis-v1/src/main/java/com/google/cloud/redis/v1/CloudRedisGrpc.java
  grpc-google-cloud-redis-v1beta1/src/main/java/com/google/cloud/redis/v1beta1/CloudRedisGrpc.java
  proto-google-cloud-redis-v1/src/main/java/com/google/cloud/redis/v1/Instance.java
  proto-google-cloud-redis-v1/src/main/java/com/google/cloud/redis/v1/InstanceOrBuilder.java
  proto-google-cloud-redis-v1/src/main/proto/google/cloud/redis/v1/cloud_redis.proto
  proto-google-cloud-redis-v1beta1/src/main/java/com/google/cloud/redis/v1beta1/Instance.java
  proto-google-cloud-redis-v1beta1/src/main/java/com/google/cloud/redis/v1beta1/InstanceOrBuilder.java
  proto-google-cloud-redis-v1beta1/src/main/proto/google/cloud/redis/v1beta1/cloud_redis.proto
  synth.metadata
Labels: automerge, cla: yes, context: full

#144 chore(java_templates): add default CODEOWNERS files for samples reviews
  .github/CODEOWNERS
  synth.metadata
Labels: automerge, cla: yes, context: full

#146 chore: turn on renovate-bot master issue for java repos
  renovate.json
  synth.metadata
Labels: automerge, cla: yes, context: full

#148 build(java): skip lint on samples directory
  .kokoro/build.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#152 fix: migrate redis/v1 to grpc_service_config
  google-cloud-redis/src/main/java/com/google/cloud/redis/v1/CloudRedisClient.java
  google-cloud-redis/src/main/java/com/google/cloud/redis/v1/CloudRedisSettings.java
  google-cloud-redis/src/main/java/com/google/cloud/redis/v1/stub/CloudRedisStub.java
  google-cloud-redis/src/main/java/com/google/cloud/redis/v1/stub/CloudRedisStubSettings.java
  google-cloud-redis/src/main/java/com/google/cloud/redis/v1/stub/GrpcCloudRedisStub.java
  google-cloud-redis/src/test/java/com/google/cloud/redis/v1/CloudRedisClientTest.java
  synth.metadata
Labels: cla: yes, context: full

#160 chore: update README versions
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: none

#163 feat(deps): adopt flatten plugin and google-cloud-shared-dependencies
  .gitignore
  google-cloud-redis/pom.xml
  grpc-google-cloud-redis-v1/pom.xml
  grpc-google-cloud-redis-v1beta1/pom.xml
  pom.xml
  proto-google-cloud-redis-v1/pom.xml
  proto-google-cloud-redis-v1beta1/pom.xml
Labels: cla: yes

#161 fix: migrate redis/v1beta1 to grpc_service_config
  google-cloud-redis/src/main/java/com/google/cloud/redis/v1beta1/CloudRedisClient.java
  google-cloud-redis/src/main/java/com/google/cloud/redis/v1beta1/CloudRedisSettings.java
  google-cloud-redis/src/main/java/com/google/cloud/redis/v1beta1/stub/CloudRedisStub.java
  google-cloud-redis/src/main/java/com/google/cloud/redis/v1beta1/stub/CloudRedisStubSettings.java
  google-cloud-redis/src/main/java/com/google/cloud/redis/v1beta1/stub/GrpcCloudRedisStub.java
  google-cloud-redis/src/test/java/com/google/cloud/redis/v1beta1/CloudRedisClientTest.java
  synth.metadata
Labels: automerge, cla: yes, context: full

#170 chore: regenerate README versions
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: none
