Repository googleapis/java-redis, pull requests merged in 2020-04, with the labels that each got.

#101 chore(deps): update dependency com.google.cloud:libraries-bom to v4.4.0 (#100)
  README.md
  synth.metadata
Labels: automerge, cla: yes

#106 chore(deps): update dependency com.google.cloud:libraries-bom to v4.4.1 (#102)
  README.md
  synth.metadata
Labels: cla: yes

#108 chore: update common templates
  .kokoro/common.sh
  README.md
  synth.metadata
Labels: automerge, cla: yes

#121 fix: flakey integration tests
  google-cloud-redis/src/test/java/com/google/cloud/redis/v1/it/ITSystemTest.java
  google-cloud-redis/src/test/java/com/google/cloud/redis/v1beta1/it/ITSystemTest.java
Labels: cla: yes

#119 chore: release 1.0.1-SNAPSHOT
  google-cloud-redis-bom/pom.xml
  google-cloud-redis/pom.xml
  grpc-google-cloud-redis-v1/pom.xml
  grpc-google-cloud-redis-v1beta1/pom.xml
  pom.xml
  proto-google-cloud-redis-v1/pom.xml
  proto-google-cloud-redis-v1beta1/pom.xml
  versions.txt
Labels: cla: yes, type: process

#117 chore: regenerate README
  README.md
  synth.metadata
Labels: automerge, cla: yes

#116 chore: update common templates
  .kokoro/common.sh
  .kokoro/dependencies.sh
  .kokoro/nightly/samples.cfg
  .kokoro/presubmit/samples.cfg
  synth.metadata
Labels: automerge, cla: yes

#122 chore(java): allow overriding the versioning section of the Java README (#495)
  README.md
  synth.metadata
Labels: automerge, cla: yes
