Repository googleapis/java-redis, pull requests merged in 2020-09, with the labels that each got.

#178 chore(docs): add cloud-RAD
  .kokoro/release/publish_javadoc.cfg
  .kokoro/release/publish_javadoc.sh
  synth.metadata
Labels: api: redis, cla: yes, context: full

#179 chore: fix versions.txt typo
  versions.txt
Labels: api: redis, cla: yes

#186 chore: regenerate common templates
  .github/CODEOWNERS
  .github/workflows/auto-release.yaml
  .github/workflows/samples.yaml
  .kokoro/continuous/dependencies.cfg
  .kokoro/continuous/java11.cfg
  .kokoro/continuous/java7.cfg
  .kokoro/continuous/java8-osx.cfg
  .kokoro/continuous/java8-win.cfg
  .kokoro/continuous/lint.cfg
  .kokoro/continuous/propose_release.cfg
  .kokoro/continuous/samples.cfg
  .kokoro/dependencies.sh
  .kokoro/nightly/dependencies.cfg
  .kokoro/nightly/lint.cfg
  .kokoro/release/stage.cfg
  synth.metadata
Labels: automerge, cla: yes, context: full

#193 [CHANGE ME] Re-generated to pick up changes from self.
  README.md
  synth.metadata
Labels: cla: yes, context: none

#191 test: fix integration test configuration
  .kokoro/continuous/integration.cfg
  .kokoro/nightly/integration.cfg
  .kokoro/presubmit/integration.cfg
Labels: cla: yes

#204 chore: regenerate README
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: none

#206 build(java): use yoshi-approver token for auto-approve
  .github/workflows/auto-release.yaml
  synth.metadata
Labels: automerge, cla: yes, context: full

#207 chore: add repo settings configuration
  .github/sync-repo-settings.yaml
Labels: api: redis, automerge, cla: yes

#214 chore: regenerate templates
  .github/readme/synth.py
  .github/workflows/auto-release.yaml
  .kokoro/continuous/readme.cfg
  .kokoro/readme.sh
  synth.metadata
Labels: automerge, cla: yes, context: full
