Repository googleapis/java-redis, pull requests merged in 2021-05, with the labels that each got.

#400 build(java): switch to release-please for release tagging
  .github/release-please.yml
  synth.metadata
Labels: api: redis, automerge, cla: yes, context: none

#401 chore: add enumeration data type to .repo-metadata.json
  .repo-metadata.json
Labels: api: redis, automerge, cla: yes

#402 chore: adding cloud-rad java xrefs
  .kokoro/release/publish_javadoc11.sh
  synth.metadata
Labels: api: redis, automerge, cla: yes, context: full

#407 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: redis, automerge, cla: yes

#411 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: redis, automerge, cla: yes

#412 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: redis, automerge, cla: yes

#415 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: redis, automerge, cla: yes

#410 build(java): remove codecov action
  .github/workflows/ci.yaml
  synth.metadata
Labels: api: redis, automerge, cla: yes, context: full

#421 feat: add gcf-owl-bot[bot] to ignoreAuthors
  .github/generated-files-bot.yml
  .kokoro/build.sh
  .kokoro/release/publish_javadoc11.sh
  synth.metadata
Labels: api: redis, cla: yes, context: full

#420 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: redis, automerge, cla: yes

#423 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: redis, automerge, cla: yes
